services:
  - type: web
    name: md-to-perfect-pdf
    env: node
    rootDir: pdf-server
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm run start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"
